---
services:
  - name: USAGov
    link: https://usa.gov
    link_alt_text: link to USA.gov
    logo: _img/Logo_USAGov.png
    logo_alt_text: USA.gov
    category: platforms
    description: "Making it easier for the public to find and understand the
      government services and information they need— anytime, anywhere. The
      program includes the Spanish-language site, USAGov en Español. "
  - name: 10x
    link: https://10x.gsa.gov/
    link_alt_text: link to 10x.gov
    logo: _img/10x-logo-alt.png
    logo_alt_text: 10x
    category: products
    description: Incrementally investing in crowdsourced technology ideas from
      federal employees to improve the public's experience with the federal
      government.
  - name: Public Benefits Studio
    link: https://digital.gov/2023/02/07/collaborate-with-the-tts-public-benefits-studio/
    link_alt_text: link to Benefits Studio GitHub repo
    logo: _img/public-benefits.png
    logo_alt_text: logo not yet available
    category: products
    description: Collaborating with benefits agencies to build shared technology
      tools and spread best practices that work across programs to support a
      simpler, less burdensome experience for low-income individuals and
      families.
  - name: Presidential Innovation Fellows
    link: https://pif.gov
    link_alt_text: link to pif.gov
    logo: _img/People_PIF.png
    logo_alt_text: PIF
    category: people
    description: Fellowship program that unites top technologists with federal leaders to tackle some of our nation's biggest challenges.
  - name: DAP
    link: https://digital.gov/guides/dap/
    link_alt_text: link to DAP website
    logo: _img/Product_DAP.png
    logo_alt_text: logo not yet available
    category: products
    description:
      Offering advanced, easy web analytics tools, training, and support
      to help the government make data-driven decisions to improve the digital
      public experience.
  - name: SAM.gov
    link: https://sam.gov/content/home
    link_alt_text: link to About SAM.gov webpage
    logo: _img/logo-sam.svg
    logo_alt_text: SAM.gov
    category: platforms
    description: The official U.S. government website for people who make, receive, and manage federal awards. This includes updating or renewing, checking the status, and searching for entity registration and exclusion records.
  - name: Digital.gov
    link: https://digital.gov
    link_alt_text: link to Digital.gov homepage
    logo: _img/digitalgov-logo.svg
    logo_alt_text: digital.gov
    category: products
    description:
      Creating community connections and providing guidance on building
      digital services to transform how the government interacts with the
      public.
  - name: Vote.gov
    link: https://vote.gov
    link_alt_text: link to Vote.gov homepage
    logo: _img/LOGO_votegov_2024.png
    logo_alt_text: Vote
    category: platforms
    description: The trusted source for accurate, official voting information from the U.S. government to the American public. Vote.gov’s mission is to make it easy for all eligible voters to understand how to register and vote.
  - name: Centers of Excellence
    link: https://coe.gsa.gov
    link_alt_text: Link to COE homepage
    logo: _img/coe-logo.svg
    logo_alt_text: Centers of Excellence
    category: people
    description:
      A centralized team of technical experts that accelerate agency-wide
      IT modernization.
  - name: Search.gov
    link: https://search.gov
    link_alt_text: link to Search.gov homepage
    logo: _img/search-gov.png
    logo_alt_text: Search.gov
    category: products
    description:
      Creating a standard search experience across government websites,
      providing the public with quick, easy access to the government information
      and services they need.
  - name: Login.gov
    link: https://login.gov
    link_alt_text: link to Login.gov homepage
    logo: _img/logo.svg
    logo_alt_text: Login.gov
    category: products
    description:
      Providing the public one account to access participating government
      services online.
  - name: 18F
    link: https://18f.gsa.gov
    link_alt_text: link to 18F homepage
    logo: _img/18f-logo.svg
    logo_alt_text: 18F
    category: people
    description: A digital consulting office that partners with agencies to help
      them build or buy digital services.
  - name: CitizenScience.gov
    link: https://science.gov
    link_alt_text: Citizen science homepage
    logo: _img/Platform_Citizenscience.gov.png
    logo_alt_text: Citizen Science
    category: platforms
    description: Supporting public engagement in scientific discovery and
      participatory research across the federal government.
  - name: Touchpoints
    link: https://touchpoints.digital.gov/
    link_alt_text: link to Touchpoints homepage
    logo: _img/touchpoints-logotype.png
    logo_alt_text: Touchpoints
    category: products
    description:
      Offers a simple, flexible, and convenient way to start collecting
      customer feedback so you can focus on serving customers rather than
      managing surveys.
  - name: Federal Risk and Authorization Management Program (FedRAMP)
    link: https://www.fedramp.gov/
    link_alt_text: link to FedRAMP homepage
    logo: _img/fedramp-logo.png
    logo_alt_text: FedRamp
    category: products
    description: Certifying the security of cloud services so that federal agencies can safely adopt and easily use authorized cloud services to meet their missions.
  - name: API.data.gov
    link: https://api.data.gov/
    link_alt_text: link to API data homepage
    logo: _img/api-data.png
    logo_alt_text: API.data.gov
    category: products
    description:
      Saving money and speeding development of federal APIs by offering a
      hosted shared service for API management. Enables greater developer
      adoption and cross-agency metrics through the use of government-wide API
      keys.
  - link: https://data.gov/
    name: Data.gov
    link_alt_text: link to Data.gov homepage
    logo: _img/data-gov.png
    logo_alt_text: Data.gov
    category: platforms
    description:
      Offering the public open access to datasets from across the federal
      government.
  - name: Challenge.gov
    link: https://challenge.gov
    link_alt_text: link to Challenge.gov homepage
    logo: _img/challenge-logo.svg
    logo_alt_text: Challenge.gov
    category: platforms
    description:
      Catalyzing public engagement and participation in innovation and
      problem solving through crowdsourcing and prize competitions.
  - name: Cloud.gov
    link: https://cloud.gov/
    link_alt_text: link to Cloud.gov homepage
    logo: _img/cloud-gov-logo.svg
    logo_alt_text: Cloud.gov
    category: products
    description: Providing federal agencies with an easy, secure way to create
      websites and deploy applications to the cloud.
  - name: U.S. Digital Corps
    link: https://digitalcorps.gsa.gov/
    link_alt_text: link to Digital Corps homepage
    logo: _img/digitalcorps_logo-alt.svg
    logo_alt_text: Digital Corps
    category: people
    description: Fellowship program for early-career technologists to launch
      impactful careers in public service and create a more effective, equitable
      government.
  - name: Federal Audit Clearinghouse (FAC)
    link: https://www.fac.gov/
    link_alt_text: link to FAC homepage
    logo: _img/FAC-logo.png
    logo_alt_text: FAC
    category: platforms
    description:
      Supporting the collection, distribution, and oversight of audits as
      guided by the Single Audit Act.
  - name: U.S. Web Design System (USWDS)
    link: https://designsystem.digital.gov/
    link_alt_text: link to USWDS homepage
    logo: _img/uswds-lg-on-white.svg
    logo_alt_text: USWDS
    category: products
    description: Providing guidance and code to transform how the government
      delivers a seamless, trustworthy and optimal digital experience to the
      public.
  - name: Regulations.gov
    link: https://www.regulations.gov/
    link_alt_text: link to eRegulations homepage
    logo: _img/Logo_Regulations.gov.png
    category: platforms
    logo_alt_text: eRulemaking logo
    description:
      Increasing access to and participation in developing regulations
      and other related documents that impact you and promoting more efficient
      and effective rulemaking through public involvement.
  - name: Electronic Subcontracting Reporting System (eSRS)
    link: https://www.esrs.gov/
    link_alt_text: link to eSRS homepage
    logo: _img/esrs.png
    logo_alt_text: Logo not yet available
    description: "A web-based reporting tool to collect subcontracting
      accomplishments and share the information with the awarding official. "
    category: platforms
  - name: Contractor Performance Assessment Reporting System (CPARS)
    link: https://cpars.gov/
    link_alt_text: link to CPARS homepage
    logo: _img/cpars.png
    logo_alt_text: CPARS
    description: CPARS contains data on federal contractors, including both past performance information and integrity records.
    category: platforms
  - name: Federal Procurement Data System
    link: https://www.fpds.gov/fpdsng_cms/index.php/en/
    link_alt_text: FPDS homepage
    logo: _img/fpds_logo.png
    logo_alt_text: Logo not yet available
    description: "Being integrated into Sam.gov, a database containing publicly
      available information about all unclassified contract actions exceeding
      the micro-purchase threshold and any modifications to those actions that
      change previously reported data, regardless of dollar value. "
    category: platforms
  - name: Federal Subaward Reporting System (FSRS)
    link: https://www.fsrs.gov/
    link_alt_text: link to FSRS homepage
    logo: _img/fsrs.png
    logo_alt_text: Logo not yet available
    description: "The reporting tool federal prime awardees use to capture and
      report subaward and executive compensation data regarding their first-tier
      subawards to meet FFATA reporting requirements. "
    category: platforms
  - name: Notify.gov
    link: https://beta.notify.gov/
    link_alt_text: link to the beta of Notify.gov's homepage
    logo: _img/notify-logo.png
    logo_alt_text: Notify.gov
    category: products
    description: The Public Benefits Studio is piloting Notify.gov, a text messaging service built by and for government. Benefits program staff can set up custom text messages in as little as 10 minutes — without a technical integration required — and at minimal cost.
